find_path(TENSORRT_INCLUDE_DIR
  NAMES NvInfer.h
  PATHS ${CUDA_TOOLKIT_ROOT_DIR} ${TENSORRT_ROOT}
  PATH_SUFFIXES include
)

find_library(TENSORRT_LIBRARY
  NAMES nvinfer
  PATHS ${CUDA_TOOLKIT_ROOT_DIR} ${TENSORRT_ROOT}
  PATH_SUFFIXES lib64 lib/x64
)

find_library(TENSORRT_LIBRARY_INFER
  NAMES nvinfer
  PATHS ${TENSORRT_ROOT}
  PATH_SUFFIXES lib64 lib/x64
)

find_library(TENSORRT_LIBRARY_ONNXPARSER
  NAMES nvonnxparser
  PATHS ${TENSORRT_ROOT}
  PATH_SUFFIXES lib64 lib/x64
)

set(TENSORRT_INCLUDE_DIRS ${TENSORRT_INCLUDE_DIR})
set(TENSORRT_LIBRARIES ${TENSORRT_LIBRARY_INFER} ${TENSORRT_LIBRARY_ONNXPARSER})

# Get version from NvInfer.h
if(EXISTS "${TENSORRT_INCLUDE_DIR}/NvInfer.h")
  file(READ "${TENSORRT_INCLUDE_DIR}/NvInfer.h" NVINFER_H_CONTENTS)
  string(REGEX MATCH "define NV_TENSORRT_MAJOR ([0-9]+)" _ "${NVINFER_H_CONTENTS}")
  set(TENSORRT_VERSION_MAJOR ${CMAKE_MATCH_1})
endif()

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(
  TENSORRT
  FOUND_VAR TENSORRT_FOUND
  REQUIRED_VARS 
    TENSORRT_INCLUDE_DIR
    TENSORRT_LIBRARY_INFER
    TENSORRT_LIBRARY_ONNXPARSER
    TENSORRT_VERSION_MAJOR
)