find_path(TENSORRT_INCLUDE_DIR
  NAMES NvInfer.h
  PATHS ${CUDA_TOOLKIT_ROOT_DIR} ${TENSORRT_ROOT} /usr/include/x86_64-linux-gnu
  PATH_SUFFIXES include
)

find_library(TENSORRT_LIBRARY_INFER
  NAMES nvinfer
  PATHS ${TENSORRT_ROOT} /usr/lib/x86_64-linux-gnu
  PATH_SUFFIXES lib64 lib/x64
)

find_library(TENSORRT_LIBRARY_ONNXPARSER
  NAMES nvonnxparser
  PATHS ${TENSORRT_ROOT} /usr/lib/x86_64-linux-gnu
  PATH_SUFFIXES lib64 lib/x64
)

if(EXISTS "${TENSORRT_INCLUDE_DIR}/NvInfer.h")
  file(READ "${TENSORRT_INCLUDE_DIR}/NvInfer.h" NVINFER_H_CONTENTS)
  string(REGEX MATCH "#define NV_TENSORRT_MAJOR ([0-9]+)" _ "${NVINFER_H_CONTENTS}")
  if(CMAKE_MATCH_1)
    set(TENSORRT_VERSION_MAJOR ${CMAKE_MATCH_1})
  endif()
endif()

set(TENSORRT_INCLUDE_DIRS ${TENSORRT_INCLUDE_DIR})
set(TENSORRT_LIBRARIES ${TENSORRT_LIBRARY_INFER} ${TENSORRT_LIBRARY_ONNXPARSER})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(TENSORRT
  REQUIRED_VARS 
    TENSORRT_INCLUDE_DIR
    TENSORRT_LIBRARY_INFER
    TENSORRT_LIBRARY_ONNXPARSER
    TENSORRT_VERSION_MAJOR
  VERSION_VAR TENSORRT_VERSION_MAJOR
)

if(TENSORRT_FOUND AND NOT TARGET TENSORRT::TENSORRT)
  add_library(TENSORRT::TENSORRT INTERFACE IMPORTED)
  set_target_properties(TENSORRT::TENSORRT PROPERTIES
    INTERFACE_INCLUDE_DIRECTORIES "${TENSORRT_INCLUDE_DIRS}"
    INTERFACE_LINK_LIBRARIES "${TENSORRT_LIBRARIES}"
  )
endif()