# Find CUDNN
find_path(CUDNN_INCLUDE_DIR
  NAMES cudnn.h
  PATHS ${CUDA_TOOLKIT_ROOT_DIR}
  PATH_SUFFIXES include cuda/include
)

find_library(CUDNN_LIBRARY
  NAMES cudnn
  PATHS ${CUDA_TOOLKIT_ROOT_DIR}
  PATH_SUFFIXES lib64 cuda/lib64 lib/x64
)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(
  CUDNN
  FOUND_VAR CUDNN_FOUND
  REQUIRED_VARS CUDNN_INCLUDE_DIR CUDNN_LIBRARY
)

if(CUDNN_FOUND AND NOT TARGET CUDNN::CUDNN)
  add_library(CUDNN::CUDNN UNKNOWN IMPORTED)
  set_target_properties(CUDNN::CUDNN PROPERTIES
    IMPORTED_LOCATION "${CUDNN_LIBRARY}"
    INTERFACE_INCLUDE_DIRECTORIES "${CUDNN_INCLUDE_DIR}"
  )
endif()